In [165]:
import pandas as pd
import numpy as np

Russel 2000 Dividend Analysis

In [166]:
df = pd.read_csv("Russell 2000 Stocks List - Characteristics.csv")
df.head()

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
0,AADI,Aadi Bioscience Inc,NaN,790.0%,0.000000,NaN,NaN,$0.00,$193.05,0,NaN,NaN,$14.77,6.80
1,AAN,Aarons Company Inc (The),Industrials,"1,261.0%",0.037135,NaN,NaN,$0.47,$389.76,NaN,NaN,NaN,$15.97,7.42
2,AAON,AAON Inc.,Industrials,"9,534.0%",0.005019,NaN,NaN,$0.48,"$5,176.96",43,21.8%,NaN,$104.06,51.07
3,AAT,American Assets Trust Inc,Real Estate,"1,808.0%",0.073009,3.1%,4.1%,$1.27,"$1,097.76",22,197.4%,NaN,$29.26,15.77
4,ABCB,Ameris Bancorp,Financial Services,"3,330.0%",0.017920,0.0%,8.4%,$0.60,"$2,310.15",7,12.7%,NaN,$53.85,28.33

Let's do some data cleaning
1. Turn Dividend Yield into a Percentage
2. Turn NaN Sector into Unknown

In [167]:
df['Dividend Yield'] = df['Dividend Yield'] * 100
df['Sector'] = df['Sector'].fillna('Unknown')
df.head()

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
0,AADI,Aadi Bioscience Inc,Unknown,790.0%,0.000000,NaN,NaN,$0.00,$193.05,0,NaN,NaN,$14.77,6.80
1,AAN,Aarons Company Inc (The),Industrials,"1,261.0%",3.713543,NaN,NaN,$0.47,$389.76,NaN,NaN,NaN,$15.97,7.42
2,AAON,AAON Inc.,Industrials,"9,534.0%",0.501862,NaN,NaN,$0.48,"$5,176.96",43,21.8%,NaN,$104.06,51.07
3,AAT,American Assets Trust Inc,Real Estate,"1,808.0%",7.300885,3.1%,4.1%,$1.27,"$1,097.76",22,197.4%,NaN,$29.26,15.77
4,ABCB,Ameris Bancorp,Financial Services,"3,330.0%",1.791973,0.0%,8.4%,$0.60,"$2,310.15",7,12.7%,NaN,$53.85,28.33

Let's find the best dividends by yield - first we should drop anything with a yield below 7%

In [168]:
df = df.drop(df[df['Dividend Yield'] < 7].index)
df = df.sort_values(by=['Dividend Yield'], ascending = False)
df.head()

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
1695,VIA,Via Renewables Inc,Unknown,945.0%,27.551672,0.0%,0.0%,$2.60,$30.11,0,NaN,0.8,$41.11,9.29
822,IVR,Invesco Mortgage Capital Inc,Real Estate,"1,110.0%",21.635180,344.4%,-1.0%,$2.40,$462.28,NaN,NaN,NaN,$15.57,8.81
1164,ORC,Orchid Island Capital Inc,Real Estate,997.0%,19.257773,0.0%,19.7%,$2.46,$390.17,NaN,NaN,NaN,$13.72,7.17
147,ARR,ARMOUR Residential REIT Inc,Real Estate,509.0%,18.860511,-20.0%,-4.4%,$1.02,$995.16,NaN,NaN,NaN,$6.69,3.77
717,HMST,HomeStreet Inc,Financial Services,603.0%,18.299261,NaN,NaN,$1.10,$113.21,2,40.1%,1.1,$37.07,4.61

Now let's find out the average dividend yield and count of each company per sector

In [169]:
dt = df.groupby(['Sector'], dropna = False)[['Dividend Yield']].agg('mean').sort_values(by=['Dividend Yield'], ascending = False)
dt['Count'] = df.groupby(['Sector'], dropna = False)[['Ticker']].agg('count')
dt

                        Dividend Yield  Count
Sector
Unknown                      13.970582     11
Real Estate                  12.447593     38
Industrials                  11.900035      5
Energy                       11.441044      4
Consumer Defensive           10.967530      1
Financial Services            9.784621      9
Healthcare                    8.733624      1
Communication Services        8.722456      2
Basic Materials               8.423718      3
Consumer Cyclical             8.237036      4
Technology                    7.047216      1

Let's grab the 11 unknown sector dividend yields, and put them into categories

In [170]:
df[df['Sector'] == 'Unknown']

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
1695,VIA,Via Renewables Inc,Unknown,945.0%,27.551672,0.0%,0.0%,$2.60,$30.11,0,NaN,0.8,$41.11,9.2900
119,AOMR,Angel Oak Mortgage REIT Inc,Unknown,774.0%,17.075420,NaN,NaN,$1.32,$192.57,0,NaN,NaN,$13.61,4.0700
42,AFCG,AFC Gamma Inc,Unknown,"1,281.0%",16.480538,NaN,NaN,$2.11,$262.05,0,NaN,NaN,$16.94,9.9100
304,CMTG,Claros Mortgage Trust Inc,Unknown,"1,085.0%",16.374665,NaN,NaN,$1.78,"$1,501.38",0,NaN,NaN,$17.82,10.0800
1320,REFI,Chicago Atlantic Real Estate Finance Inc,Unknown,"1,505.0%",14.980965,NaN,NaN,$2.25,$272.23,0,NaN,NaN,$16.22,12.4700
1370,RTL,Necessity Retail REIT Inc (The),Unknown,625.0%,13.600000,NaN,NaN,$0.79,$838.69,0,NaN,1.0,$7.25,4.4500
833,JOAN,JOANN Inc,Unknown,91.2%,12.064049,NaN,NaN,$0.11,$37.54,0,NaN,NaN,$11.41,0.9118
949,MATV,Mativ Holdings Inc,Unknown,"1,475.0%",10.518578,NaN,NaN,$1.55,$808.92,NaN,NaN,NaN,$27.86,14.5900
537,FBRT,Franklin BSP Realty Trust Inc.,Unknown,"1,354.0%",10.042347,NaN,NaN,$1.36,"$1,114.08",21,210.7%,NaN,$14.55,9.7600
838,JXN,Jackson Financial Inc,Unknown,"2,893.0%",7.878619,NaN,NaN,$2.28,"$2,386.45",0,NaN,NaN,$47.80,21.9800
1209,PFC,Premier Financial Corp,Unknown,"1,642.0%",7.109544,3.3%,12.8%,$1.17,$586.66,6,44.4%,0.9,$29.19,13.6000

In [171]:
def replace(index, sector):
    df.at[index, 'Sector'] = sector

In [172]:
#Via Renewables = Energy
replace(1695, 'Energy')
#Angel Oak Mortgage = Real Estate
replace(119, 'Real Estate')
#AFC Gamma = Real Estate
replace(42, 'Real Estate')
#Claros Mortgage Trust = Real Estate
replace(304, 'Real Estate')
#Chicago Atlantic Real Estate Finance = Real Estate
replace(1320, 'Real Estate')
#Necessity Retail REIT = Real Estate
replace(1370, 'Real Estate')
#JOANN = Consumer Cyclical
replace(833, 'Consumer Cyclical')
#Mativ Holdings = Basic Materials
replace(949, 'Basic Materials')
#Franklin BSP Realty Trust = Real Estate
replace(537, 'Real Estate')
#Jackson Financial = Financial Services
replace(838, 'Financial Services')
#Premier Financial = Financial Services
replace(1209, 'Financial Services')

Let's look at the breakdown of high div yield companies again

In [173]:
dt = df.groupby(['Sector'], dropna = False)[['Dividend Yield']].agg('mean').sort_values(by=['Dividend Yield'], ascending = False)
dt['Count'] = df.groupby(['Sector'], dropna = False)[['Ticker']].agg('count')
dt

                        Dividend Yield  Count
Sector
Energy                       14.663170      5
Real Estate                  12.762783     44
Industrials                  11.900035      5
Consumer Defensive           10.967530      1
Financial Services            9.368159     11
Consumer Cyclical             9.002439      5
Basic Materials               8.947433      4
Healthcare                    8.733624      1
Communication Services        8.722456      2
Technology                    7.047216      1

Now lets look at the 5 top dividend yields from each Sector - let's make a function to do this quickly

In [174]:
def yield_by_sector(sector_name):
    table = df[df['Sector'] == sector_name]
    table = table.sort_values(by=['Dividend Yield'], ascending = False)
    display(table.head())

In [175]:
categories = []
for cat_name in df['Sector']:
    if cat_name not in categories:
        categories.append(cat_name)

for cat_name in categories:
    print(f"{cat_name}\n")
    yield_by_sector(cat_name)

Energy

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
1695,VIA,Via Renewables Inc,Energy,945.0%,27.551672,0.0%,0.0%,$2.60,$30.11,0,NaN,0.8,$41.11,9.29
134,ARCH,Arch Resources Inc,Energy,"11,148.0%",14.837899,NaN,NaN,$16.54,"$2,081.79",2,27.1%,NaN,$173.06,102.42
595,FRO,Frontline Plc,Energy,"1,435.0%",12.958603,NaN,NaN,$1.86,"$3,194.64",5,63.3%,NaN,$17.63,6.79
569,FLNG,Flex Lng Ltd,Energy,"3,007.0%",9.890801,NaN,NaN,$2.97,"$1,639.43",0,NaN,NaN,$37.97,23.51
412,DHT,DHT Holdings Inc,Energy,835.0%,8.076874,"1,050.0%",63.0%,$0.67,"$1,360.94",12,94.6%,NaN,$11.79,5.17

Real Estate

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
822,IVR,Invesco Mortgage Capital Inc,Real Estate,"1,110.0%",21.635180,344.4%,-1.0%,$2.40,$462.28,NaN,NaN,NaN,$15.57,8.81
1164,ORC,Orchid Island Capital Inc,Real Estate,997.0%,19.257773,0.0%,19.7%,$2.46,$390.17,NaN,NaN,NaN,$13.72,7.17
147,ARR,ARMOUR Residential REIT Inc,Real Estate,509.0%,18.860511,-20.0%,-4.4%,$1.02,$995.16,NaN,NaN,NaN,$6.69,3.77
1630,TWO,Two Harbors Investment Corp,Real Estate,"1,317.0%",18.223235,252.9%,30.5%,$2.40,"$1,273.08",NaN,NaN,NaN,$19.18,11.20
1309,RC,Ready Capital Corp,Real Estate,"1,069.0%",17.622792,-38.1%,-8.3%,$1.88,"$1,183.87",7,147.2%,NaN,$12.64,8.75

Financial Services

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
717,HMST,HomeStreet Inc,Financial Services,603.0%,18.299261,NaN,NaN,$1.10,$113.21,2,40.1%,1.1,$37.07,4.61
464,EFC,Ellington Financial Inc,Financial Services,"1,330.0%",13.533835,0.0%,0.0%,$1.71,$893.25,NaN,NaN,NaN,$14.76,9.96
1339,RILY,B. Riley Financial Inc,Financial Services,"4,193.0%",8.970225,0.0%,32.0%,$3.76,"$1,179.73",NaN,NaN,1.8,$53.13,23.52
467,EGBN,Eagle Bancorp Inc (MD),Financial Services,"2,113.0%",8.367543,NaN,NaN,$1.77,$649.04,5,47.1%,NaN,$50.22,16.72
1732,WASH,"Washington Trust Bancorp, Inc.",Financial Services,"2,691.0%",8.324043,3.7%,5.4%,$2.71,$457.99,7,69.0%,NaN,$53.77,22.26

Industrials

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
649,GOGL,Golden Ocean Group Limited,Industrials,770.0%,15.619278,NaN,NaN,$1.20,"$1,543.74",5,73.8%,0.9,$11.71,6.92
644,GNK,Genco Shipping & Trading Limited,Industrials,"1,398.0%",13.267289,NaN,NaN,$1.85,$594.26,0,NaN,NaN,$19.13,10.92
1422,SFL,SFL Corporation Ltd,Industrials,908.0%,10.572687,9.1%,-7.3%,$0.91,"$1,258.14",8,76.8%,NaN,$10.45,7.91
797,INSW,International Seaways Inc,Industrials,"3,746.0%",10.054433,NaN,NaN,$3.77,"$1,844.15",3,32.8%,NaN,$50.92,16.99
1049,NAT,Nordic American Tankers Ltd,Industrials,368.0%,9.986488,650.0%,49.6%,$0.37,$768.37,9,84.6%,NaN,$4.30,1.63

Consumer Cyclical

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
833,JOAN,JOANN Inc,Consumer Cyclical,91.2%,12.064049,NaN,NaN,$0.11,$37.54,0,NaN,NaN,$11.41,0.9118
383,CWH,Camping World Holdings Inc,Consumer Cyclical,"2,762.0%",9.051412,0.0%,53.6%,$2.41,"$1,229.09",13,133.9%,NaN,$30.90,18.2900
593,FRG,Franchise Group Inc,Consumer Cyclical,"2,880.0%",8.371252,NaN,NaN,$2.41,"$1,012.97",0,NaN,NaN,$36.00,21.5700
228,CATO,Cato Corp.,Consumer Cyclical,820.0%,8.049268,NaN,NaN,$0.66,$151.53,NaN,NaN,NaN,$12.70,7.7500
972,MED,Medifast Inc,Consumer Cyclical,"8,828.0%",7.476212,0.6%,28.0%,$6.42,$961.12,7,50.2%,NaN,$183.52,77.6700

Consumer Defensive

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
217,CALM,"Cal-Maine Foods, Inc.",Consumer Defensive,"4,442.0%",10.96753,NaN,NaN,$4.87,"$1,962.73",3,31.3%,0.2,$58.66,42.16

Basic Materials

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
949,MATV,Mativ Holdings Inc,Basic Materials,"1,475.0%",10.518578,NaN,NaN,$1.55,$808.92,NaN,NaN,NaN,$27.86,14.59
869,KRO,"Kronos Worldwide, Inc.",Basic Materials,862.0%,8.816705,0.0%,2.2%,$0.74,$991.80,31,267.8%,NaN,$18.09,7.59
1617,TSE,Trinseo PLC,Basic Materials,"1,226.0%",8.808335,-56.3%,-18.9%,$1.08,$430.89,NaN,NaN,NaN,$42.41,11.79
1564,TG,Tredegar Corp.,Basic Materials,663.0%,7.646113,8.3%,3.4%,$0.51,$225.33,20,155.8%,NaN,$12.08,5.85

Communication Services

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
1556,TDS,"Telephone And Data Systems, Inc.",Communication Services,728.0%,10.164835,2.8%,2.9%,$0.71,$765.35,NaN,NaN,NaN,$16.33,6.28
421,DLX,Deluxe Corp.,Communication Services,"1,606.0%",7.280076,0.0%,0.0%,$1.17,$697.98,12,86.6%,NaN,$24.01,13.35

Healthcare

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
1207,PETS,"Petmed Express, Inc.",Healthcare,"1,374.0%",8.733624,0.0%,2.1%,$1.19,$290.92,"1,249","10,317.0%",NaN,$23.28,13.27

Technology

,Ticker,Name,Sector,Price,Dividend Yield,1-Year Dividend Growth,5-Year Dividend Growth (Annualized),Dividends Per Share (TTM),Market Cap ($M),Trailing P/E Ratio,Payout Ratio,Beta,52-Week High,52-Week Low
1779,XRX,Xerox Holdings Corp,Technology,"1,419.0%",7.047216,NaN,NaN,$0.97,"$2,227.24",NaN,NaN,NaN,$18.42,11.4